### ISSUE TITLE
Add error utils function for handling biometric errors

### ISSUE THREAD

**Issue by carmenlau** [authgear/authgear-sdk-ios#62]
Currently when encountering error in biometric api, we throw the original error from the native api to user. For user to handle the error more easily, we should provide utils function for user to identify errors, like what we did in js sdk.

https://github.com/authgear/authgear-sdk-js/blob/master/packages/authgear-react-native/src/error.ts#L82

**Comment by louischan-oursky** [comment]
## Error representation on iOS

On iOS 14.5, [NSError has a new property named underlyingErrors](https://developer.apple.com/documentation/foundation/nserror/3738169-underlyingerrors?language=objc). Previously, there is no native way to wrap error.

## Error representation on Android

Java's exception has [getCause](https://docs.oracle.com/javase/7/docs/api/java/lang/Throwable.html#getCause()) method since Java 1.4

## Error representation on JavaScript

[The builtin Error class](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error) does not support error wrapping.

## Summary on error representation

Only Java supports error wrapping out of the box. If we want to introduce error wrapping to report underlying error, we have to introduce our own set of error classes.
